#!/usr/bin/env bash

mkdir -p $HOME/.virtualenvs/

cd $HOME/.virtualenvs/

# Setup virtualenv
if [ ! -d "venv" ]; then
  echo "Setting up virtualenv..."
  virtualenv --system-site-packages -p python3 venv 
fi

source /etc/bash_completion

cd /db_backups

if [ -f $HOME/.bashrc ]; then
  source $HOME/.bashrc
fi

source $HOME/.virtualenvs/venv/bin/activate

# Start bash
bash -l
